package examples

















































































































































































}	fmt.Printf("❌ ERROR: "+format+"\n", v...)func (sl *SimpleLogger) Errorf(format string, v ...interface{}) {}	fmt.Printf(format+"\n", v...)func (sl *SimpleLogger) Printf(format string, v ...interface{}) {type SimpleLogger struct{}// SimpleLogger implementation}	fmt.Printf("\n📊 Full result as JSON:\n%s\n", string(jsonData))	jsonData, _ := json.MarshalIndent(result, "", "  ")	// Pretty print as JSON	}		fmt.Printf("    %s: %v\n", key, value)	for key, value := range result.Results {	fmt.Printf("  Extractions:\n")	fmt.Printf("  Execution: %dms\n", result.ExecutionTime)	fmt.Printf("  URL: %s\n", result.URL)	fmt.Printf("  Status: %s\n", result.Status)	fmt.Printf("\n✅ Workflow Result:\n")	}		return		fmt.Printf("❌ Error: %v\n", err)	if err != nil {	})		"to":   "SFO",		"from": "AMS",	result, err := executor.Execute(ctx, workflow, map[string]string{	executor := scraper.NewWorkflowExecutor(browser, logger)	fmt.Println("\nTesting workflow: AMS → SFO")	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)	}		},			},				Type:    "string",				Pattern: `CO₂\s*amount[:\s]*(\d+[\d\.]*)\s*t`,			"emissions_co2": {			},				Type:    "string",				Pattern: `(\d+[\d\.]*)\s*km`,			"distance_km": {		Extractions: map[string]scraper.ExtractionRule{		},			},				Wait:     3000,				Keys:     []string{"Enter"},				Selector: "input[id=\"flight_calculator_to\"]",				Action:   "keyboard",				Name:     "Submit",			{			},				Wait:     1500,				Keys:     []string{"ArrowDown", "Enter"},				Selector: "input[id=\"flight_calculator_to\"]",				Action:   "keyboard",				Name:     "Select To",			{			},				Value:    "${to}",				Selector: "input[id=\"flight_calculator_to\"]",				Action:   "fill",				Name:     "Fill To",			{			},				Wait:     1500,				Keys:     []string{"ArrowDown", "Enter"},				Selector: "input[id=\"flight_calculator_from\"]",				Action:   "keyboard",				Name:     "Select From",			{			},				Value:    "${from}",				Selector: "input[id=\"flight_calculator_from\"]",				Action:   "fill",				Name:     "Fill From",			{			},				Wait:     1000,				Optional: true,				Selector: "button:has-text(\"Accept\")",				Action:   "click",				Name:     "Dismiss Consent",			{		Actions: []scraper.WorkflowAction{		WaitUntil: "networkidle",		URL:       "https://co2.myclimate.org/en/flight_calculators/new",		Name:      "MyClimate Flight (via Workflow)",	workflow := &scraper.WorkflowDefinition{	// Define a workflow inlinefunc testWorkflowExecutor(browser pw.Browser, logger scraper.Logger) {}	fmt.Printf("\n📊 Full result as JSON:\n%s\n", string(jsonData))	jsonData, _ := json.MarshalIndent(result, "", "  ")	// Pretty print as JSON	fmt.Printf("  Execution: %dms\n", result.ExecutionTime)	fmt.Printf("  Emissions: %s kg CO2\n", result.EmissionsCO2)	fmt.Printf("  Distance: %s km\n", result.DistanceKm)	fmt.Printf("  To: %s\n", result.To)	fmt.Printf("  From: %s\n", result.From)	fmt.Printf("  Status: %s\n", result.Status)	fmt.Printf("\n✅ Results:\n")	}		return		fmt.Printf("❌ Error: %v\n", err)	if err != nil {	result, err := myclimate.ScrapeFlightEmissions(ctx, "CDG", "LHR", 1, "ECONOMY")	myclimate := scraper.NewMyClimate(browser, logger)	fmt.Println("\nTesting: CDG → LHR")	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)func testMyClimateScraper(browser pw.Browser, logger scraper.Logger) {}	testWorkflowExecutor(browser, logger)	fmt.Println("=" * 60)	fmt.Println("TEST 2: Workflow Executor (Generic)")	fmt.Println("\n" + "=" * 60)	// Test 2: Workflow Executor	testMyClimateScraper(browser, logger)	fmt.Println("=" * 60)	fmt.Println("TEST 1: MyClimate Flight Scraper (Direct)")	fmt.Println("\n" + "=" * 60)	// Test 1: MyClimate Scraper	logger := &SimpleLogger{}	// Create logger	fmt.Println("      ✅ Browser ready")	defer browser.Close()	}		os.Exit(1)		fmt.Printf("❌ Launch failed: %v\n", err)	if err != nil {	browser, err := pw.Chromium.Launch()	fmt.Println("[2/3] Launching Chromium browser...")	// Launch browser	}		os.Exit(1)		fmt.Printf("❌ Install failed: %v\n", err)	if err := pw.Install(); err != nil {	fmt.Println("\n[1/3] Installing Playwright...")	// Step 1: Install and launch browser	fmt.Println("=" * 60)	fmt.Println("🚀 Go-Playwright Scraper Test")func main() {// This can be compiled as a standalone test program// Example: How to use the Go-Playwright scrapers directly)	pw "github.com/playwright-community/playwright-go"	"your_module/services/playwright_scraper/scraper"	"os"	"fmt"	"encoding/json"	"context"import (package main