kind: pipeline
type: docker
name: build-deploy-k8s

platform:
  arch: arm64
  os: linux

steps:
  - name: build-push-monitor-ui
    image: alpine:latest
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - apk add --no-cache docker
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - test -f secure/customer_public.pem || { echo "secure/customer_public.pem not found"; exit 1; }
      - test -f secure/vendor_public.pem || { echo "secure/vendor_public.pem not found"; exit 1; }
      - docker build -f Dockerfile.monitor-ui.secure --build-arg CUSTOMER_PUBLIC_KEY=secure/customer_public.pem --build-arg VENDOR_PUBLIC_KEY=secure/vendor_public.pem -t $DOCKER_USERNAME/monitor-ui:secure .
      - docker push $DOCKER_USERNAME/monitor-ui:secure
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password

  - name: build-push-fsm-server
    image: alpine:latest
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - apk add --no-cache docker
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - test -f secure/customer_public.pem || { echo "secure/customer_public.pem not found"; exit 1; }
      - test -f secure/vendor_public.pem || { echo "secure/vendor_public.pem not found"; exit 1; }
      - docker build -f Dockerfile.fsm.secure --build-arg CUSTOMER_PUBLIC_KEY=secure/customer_public.pem --build-arg VENDOR_PUBLIC_KEY=secure/vendor_public.pem -t $DOCKER_USERNAME/fsm-server:secure .
      - docker push $DOCKER_USERNAME/fsm-server:secure
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password

  - name: build-push-data-processor
    image: alpine:latest
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - apk add --no-cache docker
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - test -f secure/customer_public.pem || { echo "secure/customer_public.pem not found"; exit 1; }
      - test -f secure/vendor_public.pem || { echo "secure/vendor_public.pem not found"; exit 1; }
      - docker build -f Dockerfile.news-ingestor.secure --build-arg CUSTOMER_PUBLIC_KEY=secure/customer_public.pem --build-arg VENDOR_PUBLIC_KEY=secure/vendor_public.pem -t $DOCKER_USERNAME/data-processor:secure .
      - docker push $DOCKER_USERNAME/data-processor:secure
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password

  - name: build-push-knowledge-builder
    image: alpine:latest
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - apk add --no-cache docker
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - test -f secure/customer_public.pem || { echo "secure/customer_public.pem not found"; exit 1; }
      - test -f secure/vendor_public.pem || { echo "secure/vendor_public.pem not found"; exit 1; }
      - docker build -f Dockerfile.wiki-bootstrapper.secure --build-arg CUSTOMER_PUBLIC_KEY=secure/customer_public.pem --build-arg VENDOR_PUBLIC_KEY=secure/vendor_public.pem -t $DOCKER_USERNAME/knowledge-builder:secure .
      - docker push $DOCKER_USERNAME/knowledge-builder:secure
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password

  - name: build-push-wiki-summarizer
    image: alpine:latest
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - apk add --no-cache docker
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - test -f secure/customer_public.pem || { echo "secure/customer_public.pem not found"; exit 1; }
      - test -f secure/vendor_public.pem || { echo "secure/vendor_public.pem not found"; exit 1; }
      - docker build -f Dockerfile.wiki-summarizer.secure --build-arg CUSTOMER_PUBLIC_KEY=secure/customer_public.pem --build-arg VENDOR_PUBLIC_KEY=secure/vendor_public.pem -t $DOCKER_USERNAME/wiki-summarizer:secure .
      - docker push $DOCKER_USERNAME/wiki-summarizer:secure
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password

  - name: build-push
    image: alpine:latest
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - apk add --no-cache docker findutils
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - echo "Workspace contents:" && ls -la
      - echo "Top-level dirs:" && find . -maxdepth 2 -type d | sort
      # Build secure-packaged images (uses public build keys in repo)
      - test -f secure/customer_public.pem || { echo "secure/customer_public.pem not found"; exit 1; }
      - test -f secure/vendor_public.pem || { echo "secure/vendor_public.pem not found"; exit 1; }
      - docker build -f Dockerfile.principles.secure --build-arg CUSTOMER_PUBLIC_KEY=secure/customer_public.pem --build-arg VENDOR_PUBLIC_KEY=secure/vendor_public.pem -t $DOCKER_USERNAME/principles-server:secure .
      - docker push $DOCKER_USERNAME/principles-server:secure
      - docker build -f Dockerfile.hdn.secure --build-arg CUSTOMER_PUBLIC_KEY=secure/customer_public.pem --build-arg VENDOR_PUBLIC_KEY=secure/vendor_public.pem -t $DOCKER_USERNAME/hdn-server:secure .
      - docker push $DOCKER_USERNAME/hdn-server:secure
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password

  - name: build-goal-binary
    image: golang:1.25-alpine
    commands:
      - apk add --no-cache git build-base
      - go version
      - ls -la && test -d cmd/goal-manager
      - mkdir -p bin
      - GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o bin/goal-manager ./cmd/goal-manager
      - ls -la bin

  - name: build-push-goal
    image: alpine:latest
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - apk add --no-cache docker
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - ls -la bin && test -f bin/goal-manager
      # Build secure-packaged goal-manager
      - test -f secure/customer_public.pem || { echo "secure/customer_public.pem not found"; exit 1; }
      - test -f secure/vendor_public.pem || { echo "secure/vendor_public.pem not found"; exit 1; }
      - docker build -f Dockerfile.goal-manager.secure --build-arg CUSTOMER_PUBLIC_KEY=secure/customer_public.pem --build-arg VENDOR_PUBLIC_KEY=secure/vendor_public.pem -t $DOCKER_USERNAME/goal-manager:secure .
      - docker push $DOCKER_USERNAME/goal-manager:secure
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password

  - name: deploy
    image: alpine:latest
    commands:
      - apk add --no-cache curl openssh-client sshpass kubectl
      - mkdir -p ~/.ssh
      - ssh-keyscan -H 192.168.1.63 >> ~/.ssh/known_hosts
      - echo '#!/bin/sh' > apply.sh
      - echo 'set -e' >> apply.sh
      - echo 'cd "$HOME"' >> apply.sh
      # Only create secure token secrets if they don't exist (don't overwrite existing ones)
      - echo "kubectl -n agi get secret secure-customer || kubectl -n agi create secret generic secure-customer --from-literal=token=\"$SECURE_CUSTOMER_TOKEN\"" >> apply.sh
      - echo "kubectl -n agi get secret secure-vendor || kubectl -n agi create secret generic secure-vendor --from-literal=token=\"$SECURE_VENDOR_TOKEN\"" >> apply.sh
      # Create FSM ConfigMap
      - echo "kubectl delete configmap fsm-config -n agi --ignore-not-found=true" >> apply.sh
      - echo 'kubectl create configmap fsm-config -n agi --from-file=artificial_mind.yaml=./k3s/fsm/config/artificial_mind.yaml' >> apply.sh
      - echo 'kubectl delete svc principles-server -n agi --ignore-not-found=true' >> apply.sh
      - echo 'kubectl delete deploy principles-server -n agi --ignore-not-found=true' >> apply.sh
      - echo 'kubectl delete svc hdn-server -n agi --ignore-not-found=true' >> apply.sh
      - echo 'kubectl delete deploy hdn-server -n agi --ignore-not-found=true' >> apply.sh
      - echo 'kubectl delete deploy hdn-server-rpi58 -n agi --ignore-not-found=true' >> apply.sh
      - echo 'kubectl delete svc goal-manager -n agi --ignore-not-found=true' >> apply.sh
      - echo 'kubectl delete deploy goal-manager -n agi --ignore-not-found=true' >> apply.sh
      - echo 'kubectl delete svc fsm-server -n agi --ignore-not-found=true' >> apply.sh
      - echo 'kubectl delete deploy fsm-server -n agi --ignore-not-found=true' >> apply.sh
      - echo 'kubectl delete deploy fsm-server-rpi58 -n agi --ignore-not-found=true' >> apply.sh
      - echo 'kubectl delete svc monitor-ui -n agi --ignore-not-found=true' >> apply.sh
      - echo 'kubectl delete deploy monitor-ui -n agi --ignore-not-found=true' >> apply.sh
      - echo 'kubectl apply -f ./k3s/principles-server.yaml' >> apply.sh
      - echo 'kubectl apply -f ./k3s/hdn-server-rpi58.yaml' >> apply.sh
      - echo 'kubectl apply -f ./k3s/goal-manager.yaml' >> apply.sh
      - echo 'kubectl apply -f ./k3s/fsm-server-rpi58.yaml' >> apply.sh
      - echo 'kubectl apply -f ./k3s/monitor-ui.yaml' >> apply.sh
      - echo 'kubectl apply -f ./k3s/wiki-summarizer-cronjob.yaml' >> apply.sh
      - echo 'kubectl set image deployment/principles-server principles-server='$DOCKER_USERNAME'/principles-server:secure -n agi' >> apply.sh
      - echo 'kubectl set image deployment/hdn-server-rpi58 hdn-server='$DOCKER_USERNAME'/hdn-server:secure -n agi' >> apply.sh
      - echo 'kubectl set image deployment/goal-manager goal-manager='$DOCKER_USERNAME'/goal-manager:secure -n agi' >> apply.sh
      - echo 'kubectl set image deployment/fsm-server-rpi58 fsm-server='$DOCKER_USERNAME'/fsm-server:secure -n agi' >> apply.sh
      - echo 'kubectl set image deployment/monitor-ui monitor-ui='$DOCKER_USERNAME'/monitor-ui:secure -n agi' >> apply.sh
      - echo 'kubectl rollout status deployment/principles-server -n agi' >> apply.sh
      - echo 'kubectl rollout status deployment/hdn-server-rpi58 -n agi' >> apply.sh
      - echo 'kubectl rollout status deployment/goal-manager -n agi' >> apply.sh
      - echo 'kubectl rollout status deployment/fsm-server-rpi58 -n agi' >> apply.sh
      - echo 'kubectl rollout status deployment/monitor-ui -n agi' >> apply.sh
      - chmod +x apply.sh
      - sshpass -p "$SSH_PASSWORD" scp -r k3s pi@192.168.1.63:~/
      - sshpass -p "$SSH_PASSWORD" scp apply.sh pi@192.168.1.63:~/
      - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no pi@192.168.1.63 './apply.sh'
    environment:
      SSH_PASSWORD:
        from_secret: SSH_PASSWORD
      DOCKER_USERNAME:
        from_secret: docker_username
      SECURE_CUSTOMER_TOKEN:
        from_secret: secure_customer_token
      SECURE_VENDOR_TOKEN:
        from_secret: secure_vendor_token

volumes:
  - name: docker
    host:
      path: /run/user/1000/docker.sock

trigger:
  event:
    - push
    - custom
