version: "3.9"

# Docker Compose configuration for x86_64 systems
# This file uses x86_64 specific images and optimizations

services:
  redis:
    image: redis:7-alpine
    container_name: agi-redis-x86
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: agi-weaviate-x86
    ports:
      - "8080:8080"   # HTTP
    volumes:
      - ./data/weaviate:/var/lib/weaviate
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai
      - CLUSTER_HOSTNAME=node1
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  neo4j:
    image: neo4j:5.15-community
    container_name: agi-neo4j-x86
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    volumes:
      - ./data/neo4j:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test1234
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "test1234", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  nats:
    image: nats:2.9-alpine
    container_name: agi-nats-x86
    ports:
      - "4222:4222"   # NATS
      - "8222:8222"   # HTTP monitoring
    command: ["--jetstream", "--http_port", "8222", "--port", "4222"]
    volumes:
      - ./data/nats:/data
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'

  # AGI Services (using x86_64 images)
  principles-server:
    image: ${DOCKER_REGISTRY:-your-registry}/principles-server:secure-x86
    container_name: agi-principles-x86
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://agi-redis-x86:6379
      - NATS_URL=nats://agi-nats-x86:4222
      - LLM_PROVIDER=${LLM_PROVIDER:-ollama}
      - LLM_API_KEY=${LLM_API_KEY}
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
    depends_on:
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  hdn-server:
    image: ${DOCKER_REGISTRY:-your-registry}/hdn-server:secure-x86
    container_name: agi-hdn-x86
    ports:
      - "8081:8081"
    environment:
      - REDIS_URL=redis://agi-redis-x86:6379
      - NATS_URL=nats://agi-nats-x86:4222
      - WEAVIATE_URL=http://agi-weaviate-x86:8080
      - NEO4J_URI=bolt://agi-neo4j-x86:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=test1234
      - LLM_PROVIDER=${LLM_PROVIDER:-ollama}
      - LLM_API_KEY=${LLM_API_KEY}
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
    depends_on:
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
      weaviate:
        condition: service_started
      neo4j:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  fsm-server:
    image: ${DOCKER_REGISTRY:-your-registry}/fsm-server:secure-x86
    container_name: agi-fsm-x86
    ports:
      - "8083:8083"
    environment:
      - REDIS_URL=redis://agi-redis-x86:6379
      - NATS_URL=nats://agi-nats-x86:4222
      - PRINCIPLES_URL=http://agi-principles-x86:8080
      - HDN_URL=http://agi-hdn-x86:8081
      - LLM_PROVIDER=${LLM_PROVIDER:-ollama}
      - LLM_API_KEY=${LLM_API_KEY}
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
    depends_on:
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
      principles-server:
        condition: service_started
      hdn-server:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  goal-manager:
    image: ${DOCKER_REGISTRY:-your-registry}/goal-manager:secure-x86
    container_name: agi-goal-manager-x86
    ports:
      - "8084:8084"
    environment:
      - REDIS_URL=redis://agi-redis-x86:6379
      - NATS_URL=nats://agi-nats-x86:4222
      - FSM_URL=http://agi-fsm-x86:8083
      - LLM_PROVIDER=${LLM_PROVIDER:-ollama}
      - LLM_API_KEY=${LLM_API_KEY}
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
    depends_on:
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
      fsm-server:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  monitor-ui:
    image: ${DOCKER_REGISTRY:-your-registry}/monitor-ui:secure-x86
    container_name: agi-monitor-x86
    ports:
      - "8082:8082"
    environment:
      - REDIS_URL=redis://agi-redis-x86:6379
      - NATS_URL=nats://agi-nats-x86:4222
      - PRINCIPLES_URL=http://agi-principles-x86:8080
      - HDN_URL=http://agi-hdn-x86:8081
      - FSM_URL=http://agi-fsm-x86:8083
      - GOAL_MANAGER_URL=http://agi-goal-manager-x86:8084
    depends_on:
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
      principles-server:
        condition: service_started
      hdn-server:
        condition: service_started
      fsm-server:
        condition: service_started
      goal-manager:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'

# Networks
networks:
  default:
    name: agi-network-x86
    driver: bridge
