FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY telegram-bot/go.mod telegram-bot/main.go ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o telegram-bot .

FROM alpine:latest
RUN apk add --no-cache ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/telegram-bot /app/telegram-bot
ENTRYPOINT ["/app/telegram-bot"]
