apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdn-server-rpi58
  namespace: agi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdn-server-rpi58
  template:
    metadata:
      labels:
        app: hdn-server-rpi58
    spec:
      nodeSelector:
        kubernetes.io/hostname: rpi58
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: hdn-server
          image: stevef1uk/hdn-server:secure-test3
          imagePullPolicy: Always
          args: ["--domain", "/config/domain.json", "--config", "/config/config.json", "--port", "8080", "--mode", "server"]
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: QUIET
              value: "1"
            - name: DRONE_TOKEN
              value: "JnFN2PMNrjlb0r85slGbNWfYFGxD68wd"
            - name: DRONE_REPO
              value: "stevef/agi-runtime"
            - name: NEO4J_URI
              value: "bolt://neo4j.agi.svc.cluster.local:7687"
            - name: NEO4J_USER
              value: "neo4j"
            - name: NEO4J_PASS
              value: "test1234"
            - name: REDIS_URL
              value: "redis://redis.agi.svc.cluster.local:6379"
            - name: WEAVIATE_URL
              value: "http://weaviate.agi.svc.cluster.local:8080"
            - name: NATS_URL
              value: "nats://nats.agi.svc.cluster.local:4222"
            - name: PRINCIPLES_URL
              value: "http://principles-server.agi.svc.cluster.local:8080"
            - name: LLM_PROVIDER
              value: "local"
            - name: LLM_MODEL
              value: "Qwen2.5-VL-7B-Instruct:latest"
            - name: LLM_TIMEOUT_SECONDS
              value: "600"
            - name: OLLAMA_BASE_URL
              value: "http://192.168.1.45:11434/api/chat"
            - name: HDN_URL
              value: "http://localhost:8080"
            - name: SECURE_CUSTOMER_PRIVATE_PATH
              value: "/keys/customer_private.pem"
            - name: SECURE_VENDOR_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secure-vendor
                  key: token
            - name: UNPACK_WORK_DIR
              value: "/tmp/unpack"
            # Docker resource limits for Raspberry Pi
            - name: DOCKER_MEMORY_LIMIT
              value: "256m"
            - name: DOCKER_CPU_LIMIT
              value: "0.5"
            - name: DOCKER_PIDS_LIMIT
              value: "128"
            - name: DOCKER_TMPFS_SIZE
              value: "64m"
            - name: ENABLE_ARM64_TOOLS
              value: "true"
            - name: EXECUTION_METHOD
              value: "ssh"
            - name: HDN_MAX_CONCURRENT_EXECUTIONS
              value: "8"
            - name: RPI_HOST
              value: "192.168.1.63"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: customer-key
              mountPath: /keys
              readOnly: true
            - name: hdn-config
              mountPath: /config
              readOnly: true
            - name: ssh-keys
              mountPath: /root/.ssh
              readOnly: true
      volumes:
        - name: customer-key
          secret:
            secretName: secure-customer-private
        - name: hdn-config
          configMap:
            name: hdn-config
            items:
              - key: config.json
                path: config.json
              - key: domain.json
                path: domain.json
        - name: ssh-keys
          secret:
            secretName: ssh-keys
            defaultMode: 0600
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: hdn-server-rpi58
  namespace: agi
spec:
  type: ClusterIP
  selector:
    app: hdn-server-rpi58
  ports:
    - port: 8080
      targetPort: http
      name: http
