apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-ui
  namespace: agi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-ui
  template:
    metadata:
      labels:
        app: monitor-ui
    spec:
      serviceAccountName: monitor-ui
      nodeSelector:
        kubernetes.io/arch: arm64
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: monitor-ui
          image: stevef1uk/monitor-ui:secure
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              name: http
          env:
            - name: REDIS_URL
              value: "redis://redis.agi:6379"
            - name: HDN_URL
              value: "http://hdn-server-rpi58.agi.svc.cluster.local:8080"
            - name: PRINCIPLES_URL
              value: "http://principles-server.agi.svc.cluster.local:8080"
            - name: FSM_URL
              value: "http://fsm-server-rpi58.agi.svc.cluster.local:8083"
            - name: GOAL_MANAGER_URL
              value: "http://goal-manager.agi.svc.cluster.local:8090"
            - name: NATS_URL
              value: "http://nats.agi.svc.cluster.local:8223"
            - name: NEO4J_URL
              value: "http://neo4j.agi.svc.cluster.local:7474"
            - name: NEO4J_USER
              value: "neo4j"
            - name: NEO4J_PASS
              value: "test1234"
            - name: WEAVIATE_URL
              value: "http://weaviate.agi.svc.cluster.local:8080"
            # Disable background processing for testing
            - name: ENABLE_AUTO_EXECUTOR
              value: "false"
            # GPU Optimization: Reduced monitor concurrency limits
            - name: MONITOR_MAX_CONCURRENT_GOALS
              value: "2"
            - name: MONITOR_LLM_WORKER_TIMEOUT_SECONDS
              value: "120"
            # GPU Optimization: LLM request throttling (prevents GPU overload)
            - name: LLM_MAX_CONCURRENT_REQUESTS
              value: "2"
            - name: LLM_TIMEOUT
              value: "120s"
            - name: LLM_TIMEOUT_SECONDS
              value: "120"
            - name: SECURE_CUSTOMER_PRIVATE_PATH
              value: "/keys/customer_private.pem"
            - name: SECURE_VENDOR_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secure-vendor
                  key: token
            - name: UNPACK_WORK_DIR
              value: "/tmp/unpack"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 15
            failureThreshold: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: customer-key
              mountPath: /keys
              readOnly: true
      volumes:
        - name: customer-key
          secret:
            secretName: secure-customer-private
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: monitor-ui
  namespace: agi
spec:
  type: NodePort
  selector:
    app: monitor-ui
  ports:
    - port: 8082
      targetPort: http
      nodePort: 30082
      name: http

