apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: agi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: neo4j
          image: neo4j:4.4-community
          env:
            - name: NEO4J_AUTH
              value: "neo4j/test1234"
            - name: NEO4J_dbms_security_procedures_unrestricted
              value: "apoc.*"
            - name: NEO4J_PLUGINS
              value: "[\"apoc\"]"
            - name: NEO4J_dbms_memory_heap_initial__size
              value: "512m"
            - name: NEO4J_dbms_memory_heap_max__size
              value: "1G"
          ports:
            - containerPort: 7474
            - containerPort: 7687
          volumeMounts:
            - name: data
              mountPath: /data
            - name: logs
              mountPath: /logs
            - name: import
              mountPath: /var/lib/neo4j/import
            - name: plugins
              mountPath: /plugins
          livenessProbe:
            httpGet:
              path: /
              port: 7474
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 7474
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: neo4j-data
        - name: logs
          emptyDir: {}
        - name: import
          emptyDir: {}
        - name: plugins
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: agi
spec:
  type: ClusterIP
  selector:
    app: neo4j
  ports:
    - port: 7474
      targetPort: 7474
      name: http
    - port: 7687
      targetPort: 7687
      name: bolt

