apiVersion: batch/v1
kind: CronJob
metadata:
  name: news-ingestor-cronjob
  namespace: agi
spec:
  schedule: "0 * * * *"  # Every hour
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: news-ingestor
            image: stevef1uk/data-processor:secure
            imagePullPolicy: Always
            args: ["-url", "https://www.bbc.com/news", "-max", "100", "-llm", "-batch-size", "10", "-debug"]
            env:
            - name: NATS_URL
              value: "nats://nats:4222"
            # LLM configuration from secret (can be updated without changing deployment)
            - name: LLM_MODEL
              valueFrom:
                secretKeyRef:
                  name: llm-config
                  key: LLM_MODEL
            - name: OLLAMA_URL
              valueFrom:
                secretKeyRef:
                  name: llm-config
                  key: OLLAMA_URL
            - name: LLM_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: llm-config
                  key: OLLAMA_URL
            - name: LLM_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: llm-config
                  key: LLM_TIMEOUT
            - name: LLM_TIMEOUT_SECONDS
              valueFrom:
                secretKeyRef:
                  name: llm-config
                  key: LLM_TIMEOUT_SECONDS
            - name: LLM_MAX_CONCURRENT_REQUESTS
              valueFrom:
                secretKeyRef:
                  name: llm-config
                  key: LLM_MAX_CONCURRENT_REQUESTS
            # Async LLM Queue Configuration
            - name: USE_ASYNC_LLM_QUEUE
              valueFrom:
                secretKeyRef:
                  name: llm-config
                  key: USE_ASYNC_LLM_QUEUE
            - name: ASYNC_LLM_MAX_WORKERS
              valueFrom:
                secretKeyRef:
                  name: llm-config
                  key: ASYNC_LLM_MAX_WORKERS
            - name: ASYNC_LLM_TIMEOUT_SECONDS
              valueFrom:
                secretKeyRef:
                  name: llm-config
                  key: ASYNC_LLM_TIMEOUT_SECONDS
            - name: SECURE_CUSTOMER_PRIVATE_PATH
              value: "/keys/customer_private.pem"
            - name: SECURE_VENDOR_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: secure-vendor
            - name: UNPACK_WORK_DIR
              value: "/tmp/unpack"
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 256Mi
            volumeMounts:
            - name: customer-key
              mountPath: /keys
              readOnly: true
          volumes:
          - name: customer-key
            secret:
              secretName: secure-customer-private
          nodeSelector:
            kubernetes.io/arch: arm64
            performance-tier: utility
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
