apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: agi
spec:
  type: ClusterIP
  ports:
  - port: 11434
    targetPort: 11434
    name: api
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ollama
  namespace: agi
subsets:
- addresses:
  - ip: 192.168.1.53
  ports:
  - port: 11434
    name: api
