apiVersion: apps/v1
kind: Deployment
metadata:
  name: principles-server
  namespace: agi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: principles-server
  template:
    metadata:
      labels:
        app: principles-server
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
        performance-tier: main
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: principles-server
          image: stevef1uk/principles-server:secure
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
              name: http
          env:
            - name: REDIS_URL
              value: "redis://redis.agi.svc.cluster.local:6379"
            - name: SECURE_CUSTOMER_PRIVATE_PATH
              value: "/keys/customer_private.pem"
            - name: SECURE_VENDOR_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secure-vendor
                  key: token
            - name: UNPACK_WORK_DIR
              value: "/tmp/unpack"
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: customer-key
              mountPath: /keys
              readOnly: true
      volumes:
        - name: customer-key
          secret:
            secretName: secure-customer-private
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: principles-server
  namespace: agi
spec:
  type: ClusterIP
  selector:
    app: principles-server
  ports:
    - port: 8080
      targetPort: 8084
      name: http
