apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weaviate-data
  namespace: agi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
