apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secret
  namespace: agi
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "<your token>"
  TELEGRAM_CHAT_ID: "<your noitification channel ID>"
  MCP_SERVER_URL: "http://hdn-server-rpi58.agi.svc.cluster.local:8080/mcp"
  CHAT_SERVER_URL: "http://hdn-server-rpi58.agi.svc.cluster.local:8080/api/v1/chat"
  ALLOWED_TELEGRAM_USERS: "<your_id>,another_user,trusted_friend"
