apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secret
  namespace: agi
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "8545418305:AAFPE3FFH2chFAVxNH-nNQrTO_X5lKOOGys"
  MCP_SERVER_URL: "http://hdn-server-rpi58.agi.svc.cluster.local:8080/mcp"
