apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
  namespace: agi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      securityContext:
        fsGroup: 1000
      nodeSelector:
        kubernetes.io/arch: arm64
        performance-tier: main
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: weaviate
          image: semitechnologies/weaviate:1.21.2
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: QUERY_DEFAULTS_LIMIT
              value: "25"
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "true"
            - name: PERSISTENCE_DATA_PATH
              value: "/var/lib/weaviate"
            - name: DEFAULT_VECTORIZER_MODULE
              value: "none"
            - name: ENABLE_MODULES
              value: ""
            - name: CLUSTER_HOSTNAME
              value: "node1"
          volumeMounts:
            - name: storage
              mountPath: /var/lib/weaviate
          livenessProbe:
            httpGet:
              path: /v1/.well-known/live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /v1/.well-known/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: weaviate-data
---
apiVersion: v1
kind: Service
metadata:
  name: weaviate
  namespace: agi
spec:
  type: ClusterIP
  selector:
    app: weaviate
  ports:
    - port: 8080
      targetPort: http
      name: http
